apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-service
  labels:
    app: quote-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quote-service
  template:
    metadata:
      labels:
        app: quote-service
    spec:
      containers:
        - name: quote-service
          image: us-central1-docker.pkg.dev/fast-pagoda-474409-c7/microservice-registery/quote-service:latest
          ports:
            - containerPort: 8001