apiVersion: apps/v1
kind: Deployment
metadata:
  name: poem-service
  labels:
    app: poem-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poem-service
  template:
    metadata:
      labels:
        app: poem-service
    spec:
      containers:
        - name: poem-service
          image: us-central1-docker.pkg.dev/fast-pagoda-474409-c7/microservice-registery/poem-service:latest
          ports:
            - containerPort: 8000